[mgr]
ratio = [1, 4, 3]
sort_dir_first = true
show_symlink = false
linemode = "mtime"

[preview]
wrap = "yes"
max_width = 1000
max_height = 1500

[tasks]
image_bound = [10000, 10000]

[opener]
edit = [{ run = 'nvim "$@"', block = true, desc = "nvim" }]
# subl = [{ run = 'subl "$@"', desc = "subl" }]

[open]
prepend_rules = [
  { name = "*.tex", use = "subl" },
]

[plugin]
prepend_previewers = [
    { name = "*.csv", run = "rich-preview"}, # for csv files
    { name = "*.md", run = "rich-preview" }, # for markdown (.md) files
    { name = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
    { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
#    { name = "*.json", run = "rich-preview"}, # for json (.json) files
#    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]
